# -*- coding: utf-8 -*-


################################################################################
#
# WeatherLog: ui/chart_builder.py
# This module implements the function for building the Charts tab.
#
################################################################################


# Import Gtk and Gdk for the interface.
from gi.repository import Gtk


def chart_builder(self):
    """Builds the Charts tab on the main interface."""

    # Create the chart frame.
    self.chart_frame = Gtk.Box()
    self.chart_notebook = Gtk.Notebook()
    self.chart_notebook.set_tab_pos(Gtk.PositionType.LEFT)
    self.chart_frame.add(self.chart_notebook)

    # Tab 1: Temperature chart.
    self.chart_temp_box = Gtk.Box()
    self.chart_temp_box.set_hexpand(True)
    self.chart_temp_box.set_vexpand(True)
    self.chart_temp_box_lbl = Gtk.Label("Temperature")
    self.chart_temp_list = Gtk.ListStore(str, str, str, str, str, str)
    self.chart_temp_tree = Gtk.TreeView(model=self.chart_temp_list)
    self.chart_temp_day_text = Gtk.CellRendererText()
    self.chart_temp_day_col = Gtk.TreeViewColumn("Day", self.chart_temp_day_text, text=0)
    self.chart_temp_day_col.set_min_width(150)
    self.chart_temp_tree.append_column(self.chart_temp_day_col)
    self.chart_temp_value_text = Gtk.CellRendererText()
    self.chart_temp_value_col = Gtk.TreeViewColumn("Value", self.chart_temp_value_text, text=1)
    self.chart_temp_value_col.set_min_width(100)
    self.chart_temp_tree.append_column(self.chart_temp_value_col)
    self.chart_temp_avg_text = Gtk.CellRendererText()
    self.chart_temp_avg_col = Gtk.TreeViewColumn("Average Difference", self.chart_temp_value_text, text=2)
    self.chart_temp_tree.append_column(self.chart_temp_avg_col)
    self.chart_temp_low_text = Gtk.CellRendererText()
    self.chart_temp_low_col = Gtk.TreeViewColumn("Low Difference", self.chart_temp_low_text, text=3)
    self.chart_temp_tree.append_column(self.chart_temp_low_col)
    self.chart_temp_high_text = Gtk.CellRendererText()
    self.chart_temp_high_col = Gtk.TreeViewColumn("High Difference", self.chart_temp_high_text, text=4)
    self.chart_temp_tree.append_column(self.chart_temp_high_col)
    self.chart_temp_med_text = Gtk.CellRendererText()
    self.chart_temp_med_col = Gtk.TreeViewColumn("Median Difference", self.chart_temp_med_text, text=5)
    self.chart_temp_tree.append_column(self.chart_temp_med_col)
    self.chart_temp_box.pack_start(self.chart_temp_tree, fill=True, expand=True, padding=0)

    # Tab 2: Wind Chill chart.
    self.chart_chil_box = Gtk.Box()
    self.chart_chil_box_lbl = Gtk.Label("Wind Chill")
    self.chart_chil_list = Gtk.ListStore(str, str, str, str, str, str)
    self.chart_chil_tree = Gtk.TreeView(model=self.chart_chil_list)
    self.chart_chil_day_text = Gtk.CellRendererText()
    self.chart_chil_day_col = Gtk.TreeViewColumn("Day", self.chart_chil_day_text, text=0)
    self.chart_chil_day_col.set_min_width(150)
    self.chart_chil_tree.append_column(self.chart_chil_day_col)
    self.chart_chil_value_text = Gtk.CellRendererText()
    self.chart_chil_value_col = Gtk.TreeViewColumn("Value", self.chart_chil_value_text, text=1)
    self.chart_chil_value_col.set_min_width(100)
    self.chart_chil_tree.append_column(self.chart_chil_value_col)
    self.chart_chil_avg_text = Gtk.CellRendererText()
    self.chart_chil_avg_col = Gtk.TreeViewColumn("Average Difference", self.chart_chil_value_text, text=2)
    self.chart_chil_tree.append_column(self.chart_chil_avg_col)
    self.chart_chil_low_text = Gtk.CellRendererText()
    self.chart_chil_low_col = Gtk.TreeViewColumn("Low Difference", self.chart_chil_low_text, text=3)
    self.chart_chil_tree.append_column(self.chart_chil_low_col)
    self.chart_chil_high_text = Gtk.CellRendererText()
    self.chart_chil_high_col = Gtk.TreeViewColumn("High Difference", self.chart_chil_high_text, text=4)
    self.chart_chil_tree.append_column(self.chart_chil_high_col)
    self.chart_chil_med_text = Gtk.CellRendererText()
    self.chart_chil_med_col = Gtk.TreeViewColumn("Median Difference", self.chart_chil_med_text, text=5)
    self.chart_chil_tree.append_column(self.chart_chil_med_col)
    self.chart_chil_box.pack_start(self.chart_chil_tree, fill=True, expand=True, padding=0)

    # Tab 3: Precipitation chart.
    self.chart_prec_box = Gtk.Box()
    self.chart_prec_box_lbl = Gtk.Label("Precipitation")
    self.chart_prec_list = Gtk.ListStore(str, str, str, str, str, str)
    self.chart_prec_tree = Gtk.TreeView(model=self.chart_prec_list)
    self.chart_prec_day_text = Gtk.CellRendererText()
    self.chart_prec_day_col = Gtk.TreeViewColumn("Day", self.chart_prec_day_text, text=0)
    self.chart_prec_day_col.set_min_width(150)
    self.chart_prec_tree.append_column(self.chart_prec_day_col)
    self.chart_prec_value_text = Gtk.CellRendererText()
    self.chart_prec_value_col = Gtk.TreeViewColumn("Value", self.chart_prec_value_text, text=1)
    self.chart_prec_value_col.set_min_width(100)
    self.chart_prec_tree.append_column(self.chart_prec_value_col)
    self.chart_prec_avg_text = Gtk.CellRendererText()
    self.chart_prec_avg_col = Gtk.TreeViewColumn("Average Difference", self.chart_prec_value_text, text=2)
    self.chart_prec_tree.append_column(self.chart_prec_avg_col)
    self.chart_prec_low_text = Gtk.CellRendererText()
    self.chart_prec_low_col = Gtk.TreeViewColumn("Low Difference", self.chart_prec_low_text, text=3)
    self.chart_prec_tree.append_column(self.chart_prec_low_col)
    self.chart_prec_high_text = Gtk.CellRendererText()
    self.chart_prec_high_col = Gtk.TreeViewColumn("High Difference", self.chart_prec_high_text, text=4)
    self.chart_prec_tree.append_column(self.chart_prec_high_col)
    self.chart_prec_med_text = Gtk.CellRendererText()
    self.chart_prec_med_col = Gtk.TreeViewColumn("Median Difference", self.chart_prec_med_text, text=5)
    self.chart_prec_tree.append_column(self.chart_prec_med_col)
    self.chart_prec_box.pack_start(self.chart_prec_tree, fill=True, expand=True, padding=0)

    # Tab 4: Wind chart.
    self.chart_wind_box = Gtk.Box()
    self.chart_wind_box_lbl = Gtk.Label("Wind")
    self.chart_wind_list = Gtk.ListStore(str, str, str, str, str, str)
    self.chart_wind_tree = Gtk.TreeView(model=self.chart_wind_list)
    self.chart_wind_day_text = Gtk.CellRendererText()
    self.chart_wind_day_col = Gtk.TreeViewColumn("Day", self.chart_wind_day_text, text=0)
    self.chart_wind_day_col.set_min_width(150)
    self.chart_wind_tree.append_column(self.chart_wind_day_col)
    self.chart_wind_value_text = Gtk.CellRendererText()
    self.chart_wind_value_col = Gtk.TreeViewColumn("Value", self.chart_wind_value_text, text=1)
    self.chart_wind_value_col.set_min_width(100)
    self.chart_wind_tree.append_column(self.chart_wind_value_col)
    self.chart_wind_avg_text = Gtk.CellRendererText()
    self.chart_wind_avg_col = Gtk.TreeViewColumn("Average Difference", self.chart_wind_value_text, text=2)
    self.chart_wind_tree.append_column(self.chart_wind_avg_col)
    self.chart_wind_low_text = Gtk.CellRendererText()
    self.chart_wind_low_col = Gtk.TreeViewColumn("Low Difference", self.chart_wind_low_text, text=3)
    self.chart_wind_tree.append_column(self.chart_wind_low_col)
    self.chart_wind_high_text = Gtk.CellRendererText()
    self.chart_wind_high_col = Gtk.TreeViewColumn("High Difference", self.chart_wind_high_text, text=4)
    self.chart_wind_tree.append_column(self.chart_wind_high_col)
    self.chart_wind_med_text = Gtk.CellRendererText()
    self.chart_wind_med_col = Gtk.TreeViewColumn("Median Difference", self.chart_wind_med_text, text=5)
    self.chart_wind_tree.append_column(self.chart_wind_med_col)
    self.chart_wind_box.pack_start(self.chart_wind_tree, fill=True, expand=True, padding=0)

    # Tab 5: Humidity chart.
    self.chart_humi_box = Gtk.Box()
    self.chart_humi_box_lbl = Gtk.Label("Humidity")
    self.chart_humi_list = Gtk.ListStore(str, str, str, str, str, str)
    self.chart_humi_tree = Gtk.TreeView(model=self.chart_humi_list)
    self.chart_humi_day_text = Gtk.CellRendererText()
    self.chart_humi_day_col = Gtk.TreeViewColumn("Day", self.chart_humi_day_text, text=0)
    self.chart_humi_day_col.set_min_width(150)
    self.chart_humi_tree.append_column(self.chart_humi_day_col)
    self.chart_humi_value_text = Gtk.CellRendererText()
    self.chart_humi_value_col = Gtk.TreeViewColumn("Value", self.chart_humi_value_text, text=1)
    self.chart_humi_value_col.set_min_width(100)
    self.chart_humi_tree.append_column(self.chart_humi_value_col)
    self.chart_humi_avg_text = Gtk.CellRendererText()
    self.chart_humi_avg_col = Gtk.TreeViewColumn("Average Difference", self.chart_humi_value_text, text=2)
    self.chart_humi_tree.append_column(self.chart_humi_avg_col)
    self.chart_humi_low_text = Gtk.CellRendererText()
    self.chart_humi_low_col = Gtk.TreeViewColumn("Low Difference", self.chart_humi_low_text, text=3)
    self.chart_humi_tree.append_column(self.chart_humi_low_col)
    self.chart_humi_high_text = Gtk.CellRendererText()
    self.chart_humi_high_col = Gtk.TreeViewColumn("High Difference", self.chart_humi_high_text, text=4)
    self.chart_humi_tree.append_column(self.chart_humi_high_col)
    self.chart_humi_med_text = Gtk.CellRendererText()
    self.chart_humi_med_col = Gtk.TreeViewColumn("Median Difference", self.chart_humi_med_text, text=5)
    self.chart_humi_tree.append_column(self.chart_humi_med_col)
    self.chart_humi_box.pack_start(self.chart_humi_tree, fill=True, expand=True, padding=0)

    # Tab 6: Air Pressure chart.
    self.chart_airp_box = Gtk.Box()
    self.chart_airp_box_lbl = Gtk.Label("Air Pressure")
    self.chart_airp_list = Gtk.ListStore(str, str, str, str, str, str)
    self.chart_airp_tree = Gtk.TreeView(model=self.chart_airp_list)
    self.chart_airp_day_text = Gtk.CellRendererText()
    self.chart_airp_day_col = Gtk.TreeViewColumn("Day", self.chart_airp_day_text, text=0)
    self.chart_airp_day_col.set_min_width(150)
    self.chart_airp_tree.append_column(self.chart_airp_day_col)
    self.chart_airp_value_text = Gtk.CellRendererText()
    self.chart_airp_value_col = Gtk.TreeViewColumn("Value", self.chart_airp_value_text, text=1)
    self.chart_airp_value_col.set_min_width(100)
    self.chart_airp_tree.append_column(self.chart_airp_value_col)
    self.chart_airp_avg_text = Gtk.CellRendererText()
    self.chart_airp_avg_col = Gtk.TreeViewColumn("Average Difference", self.chart_airp_value_text, text=2)
    self.chart_airp_tree.append_column(self.chart_airp_avg_col)
    self.chart_airp_low_text = Gtk.CellRendererText()
    self.chart_airp_low_col = Gtk.TreeViewColumn("Low Difference", self.chart_airp_low_text, text=3)
    self.chart_airp_tree.append_column(self.chart_airp_low_col)
    high_text5 = Gtk.CellRendererText()
    self.chart_airp_high_col = Gtk.TreeViewColumn("High Difference", high_text5, text=4)
    self.chart_airp_tree.append_column(self.chart_airp_high_col)
    self.chart_airp_med_text = Gtk.CellRendererText()
    self.chart_airp_med_col = Gtk.TreeViewColumn("Median Difference", self.chart_airp_med_text, text=5)
    self.chart_airp_tree.append_column(self.chart_airp_med_col)
    self.chart_airp_box.pack_start(self.chart_airp_tree, fill=True, expand=True, padding=0)

    # Tab 7: Visibility chart.
    self.chart_visi_box = Gtk.Box()
    self.chart_visi_box_lbl = Gtk.Label("Visibility")
    self.chart_visi_list = Gtk.ListStore(str, str, str, str, str, str)
    self.chart_visi_tree = Gtk.TreeView(model=self.chart_visi_list)
    self.chart_visi_day_text = Gtk.CellRendererText()
    self.chart_visi_day_col = Gtk.TreeViewColumn("Day", self.chart_visi_day_text, text=0)
    self.chart_visi_day_col.set_min_width(150)
    self.chart_visi_tree.append_column(self.chart_visi_day_col)
    self.chart_visi_value_text = Gtk.CellRendererText()
    self.chart_visi_value_col = Gtk.TreeViewColumn("Value", self.chart_visi_value_text, text=1)
    self.chart_visi_value_col.set_min_width(100)
    self.chart_visi_tree.append_column(self.chart_visi_value_col)
    self.chart_visi_avg_text = Gtk.CellRendererText()
    self.chart_visi_avg_col = Gtk.TreeViewColumn("Average Difference", self.chart_visi_value_text, text=2)
    self.chart_visi_tree.append_column(self.chart_visi_avg_col)
    self.chart_visi_low_text = Gtk.CellRendererText()
    self.chart_visi_low_col = Gtk.TreeViewColumn("Low Difference", self.chart_visi_low_text, text=3)
    self.chart_visi_tree.append_column(self.chart_visi_low_col)
    self.chart_visi_high_text = Gtk.CellRendererText()
    self.chart_visi_high_col = Gtk.TreeViewColumn("High Difference", self.chart_visi_high_text, text=4)
    self.chart_visi_tree.append_column(self.chart_visi_high_col)
    self.chart_visi_med_text = Gtk.CellRendererText()
    self.chart_visi_med_col = Gtk.TreeViewColumn("Median Difference", self.chart_visi_med_text, text=5)
    self.chart_visi_tree.append_column(self.chart_visi_med_col)
    self.chart_visi_box.pack_start(self.chart_visi_tree, fill=True, expand=True, padding=0)

    # Add the tabs.
    self.chart_notebook.append_page(self.chart_temp_box, self.chart_temp_box_lbl)
    self.chart_notebook.append_page(self.chart_chil_box, self.chart_chil_box_lbl)
    self.chart_notebook.append_page(self.chart_prec_box, self.chart_prec_box_lbl)
    self.chart_notebook.append_page(self.chart_wind_box, self.chart_wind_box_lbl)
    self.chart_notebook.append_page(self.chart_humi_box, self.chart_humi_box_lbl)
    self.chart_notebook.append_page(self.chart_airp_box, self.chart_airp_box_lbl)
    self.chart_notebook.append_page(self.chart_visi_box, self.chart_visi_box_lbl)
