# -*- coding: utf-8 -*-


################################################################################
#
# WeatherLog: ui/table_builder.py
# This module implements the function for building the Tables tab.
#
################################################################################


# Import Gtk and Gdk for the interface.
from gi.repository import Gtk


def table_builder(self):
    """Builds the Tables tab on the main interface."""

    # Create the table frame.
    self.table_frame = Gtk.Box()
    self.table_notebook = Gtk.Notebook()
    self.table_notebook.set_tab_pos(Gtk.PositionType.LEFT)
    self.table_frame.add(self.table_notebook)

    # Tab 1: Temperature table.
    self.table_temp_box = Gtk.Box()
    self.table_temp_box.set_hexpand(True)
    self.table_temp_box.set_vexpand(True)
    self.table_temp_box_lbl = Gtk.Label("Temperature")
    self.table_temp_list = Gtk.ListStore(str, str, str, str, str, str)
    self.table_temp_tree = Gtk.TreeView(model=self.table_temp_list)
    self.table_temp_day_text = Gtk.CellRendererText()
    self.table_temp_day_col = Gtk.TreeViewColumn("Day", self.table_temp_day_text, text=0)
    self.table_temp_day_col.set_min_width(150)
    self.table_temp_tree.append_column(self.table_temp_day_col)
    self.table_temp_value_text = Gtk.CellRendererText()
    self.table_temp_value_col = Gtk.TreeViewColumn("Value", self.table_temp_value_text, text=1)
    self.table_temp_value_col.set_min_width(100)
    self.table_temp_tree.append_column(self.table_temp_value_col)
    self.table_temp_avg_text = Gtk.CellRendererText()
    self.table_temp_avg_col = Gtk.TreeViewColumn("Average Difference", self.table_temp_value_text, text=2)
    self.table_temp_tree.append_column(self.table_temp_avg_col)
    self.table_temp_low_text = Gtk.CellRendererText()
    self.table_temp_low_col = Gtk.TreeViewColumn("Low Difference", self.table_temp_low_text, text=3)
    self.table_temp_tree.append_column(self.table_temp_low_col)
    self.table_temp_high_text = Gtk.CellRendererText()
    self.table_temp_high_col = Gtk.TreeViewColumn("High Difference", self.table_temp_high_text, text=4)
    self.table_temp_tree.append_column(self.table_temp_high_col)
    self.table_temp_med_text = Gtk.CellRendererText()
    self.table_temp_med_col = Gtk.TreeViewColumn("Median Difference", self.table_temp_med_text, text=5)
    self.table_temp_tree.append_column(self.table_temp_med_col)
    self.table_temp_box.pack_start(self.table_temp_tree, fill=True, expand=True, padding=0)

    # Tab 2: Wind Chill table.
    self.table_chil_box = Gtk.Box()
    self.table_chil_box_lbl = Gtk.Label("Wind Chill")
    self.table_chil_list = Gtk.ListStore(str, str, str, str, str, str)
    self.table_chil_tree = Gtk.TreeView(model=self.table_chil_list)
    self.table_chil_day_text = Gtk.CellRendererText()
    self.table_chil_day_col = Gtk.TreeViewColumn("Day", self.table_chil_day_text, text=0)
    self.table_chil_day_col.set_min_width(150)
    self.table_chil_tree.append_column(self.table_chil_day_col)
    self.table_chil_value_text = Gtk.CellRendererText()
    self.table_chil_value_col = Gtk.TreeViewColumn("Value", self.table_chil_value_text, text=1)
    self.table_chil_value_col.set_min_width(100)
    self.table_chil_tree.append_column(self.table_chil_value_col)
    self.table_chil_avg_text = Gtk.CellRendererText()
    self.table_chil_avg_col = Gtk.TreeViewColumn("Average Difference", self.table_chil_value_text, text=2)
    self.table_chil_tree.append_column(self.table_chil_avg_col)
    self.table_chil_low_text = Gtk.CellRendererText()
    self.table_chil_low_col = Gtk.TreeViewColumn("Low Difference", self.table_chil_low_text, text=3)
    self.table_chil_tree.append_column(self.table_chil_low_col)
    self.table_chil_high_text = Gtk.CellRendererText()
    self.table_chil_high_col = Gtk.TreeViewColumn("High Difference", self.table_chil_high_text, text=4)
    self.table_chil_tree.append_column(self.table_chil_high_col)
    self.table_chil_med_text = Gtk.CellRendererText()
    self.table_chil_med_col = Gtk.TreeViewColumn("Median Difference", self.table_chil_med_text, text=5)
    self.table_chil_tree.append_column(self.table_chil_med_col)
    self.table_chil_box.pack_start(self.table_chil_tree, fill=True, expand=True, padding=0)

    # Tab 3: Precipitation table.
    self.table_prec_box = Gtk.Box()
    self.table_prec_box_lbl = Gtk.Label("Precipitation")
    self.table_prec_list = Gtk.ListStore(str, str, str, str, str, str)
    self.table_prec_tree = Gtk.TreeView(model=self.table_prec_list)
    self.table_prec_day_text = Gtk.CellRendererText()
    self.table_prec_day_col = Gtk.TreeViewColumn("Day", self.table_prec_day_text, text=0)
    self.table_prec_day_col.set_min_width(150)
    self.table_prec_tree.append_column(self.table_prec_day_col)
    self.table_prec_value_text = Gtk.CellRendererText()
    self.table_prec_value_col = Gtk.TreeViewColumn("Value", self.table_prec_value_text, text=1)
    self.table_prec_value_col.set_min_width(100)
    self.table_prec_tree.append_column(self.table_prec_value_col)
    self.table_prec_avg_text = Gtk.CellRendererText()
    self.table_prec_avg_col = Gtk.TreeViewColumn("Average Difference", self.table_prec_value_text, text=2)
    self.table_prec_tree.append_column(self.table_prec_avg_col)
    self.table_prec_low_text = Gtk.CellRendererText()
    self.table_prec_low_col = Gtk.TreeViewColumn("Low Difference", self.table_prec_low_text, text=3)
    self.table_prec_tree.append_column(self.table_prec_low_col)
    self.table_prec_high_text = Gtk.CellRendererText()
    self.table_prec_high_col = Gtk.TreeViewColumn("High Difference", self.table_prec_high_text, text=4)
    self.table_prec_tree.append_column(self.table_prec_high_col)
    self.table_prec_med_text = Gtk.CellRendererText()
    self.table_prec_med_col = Gtk.TreeViewColumn("Median Difference", self.table_prec_med_text, text=5)
    self.table_prec_tree.append_column(self.table_prec_med_col)
    self.table_prec_box.pack_start(self.table_prec_tree, fill=True, expand=True, padding=0)

    # Tab 4: Wind table.
    self.table_wind_box = Gtk.Box()
    self.table_wind_box_lbl = Gtk.Label("Wind")
    self.table_wind_list = Gtk.ListStore(str, str, str, str, str, str)
    self.table_wind_tree = Gtk.TreeView(model=self.table_wind_list)
    self.table_wind_day_text = Gtk.CellRendererText()
    self.table_wind_day_col = Gtk.TreeViewColumn("Day", self.table_wind_day_text, text=0)
    self.table_wind_day_col.set_min_width(150)
    self.table_wind_tree.append_column(self.table_wind_day_col)
    self.table_wind_value_text = Gtk.CellRendererText()
    self.table_wind_value_col = Gtk.TreeViewColumn("Value", self.table_wind_value_text, text=1)
    self.table_wind_value_col.set_min_width(100)
    self.table_wind_tree.append_column(self.table_wind_value_col)
    self.table_wind_avg_text = Gtk.CellRendererText()
    self.table_wind_avg_col = Gtk.TreeViewColumn("Average Difference", self.table_wind_value_text, text=2)
    self.table_wind_tree.append_column(self.table_wind_avg_col)
    self.table_wind_low_text = Gtk.CellRendererText()
    self.table_wind_low_col = Gtk.TreeViewColumn("Low Difference", self.table_wind_low_text, text=3)
    self.table_wind_tree.append_column(self.table_wind_low_col)
    self.table_wind_high_text = Gtk.CellRendererText()
    self.table_wind_high_col = Gtk.TreeViewColumn("High Difference", self.table_wind_high_text, text=4)
    self.table_wind_tree.append_column(self.table_wind_high_col)
    self.table_wind_med_text = Gtk.CellRendererText()
    self.table_wind_med_col = Gtk.TreeViewColumn("Median Difference", self.table_wind_med_text, text=5)
    self.table_wind_tree.append_column(self.table_wind_med_col)
    self.table_wind_box.pack_start(self.table_wind_tree, fill=True, expand=True, padding=0)

    # Tab 5: Humidity table.
    self.table_humi_box = Gtk.Box()
    self.table_humi_box_lbl = Gtk.Label("Humidity")
    self.table_humi_list = Gtk.ListStore(str, str, str, str, str, str)
    self.table_humi_tree = Gtk.TreeView(model=self.table_humi_list)
    self.table_humi_day_text = Gtk.CellRendererText()
    self.table_humi_day_col = Gtk.TreeViewColumn("Day", self.table_humi_day_text, text=0)
    self.table_humi_day_col.set_min_width(150)
    self.table_humi_tree.append_column(self.table_humi_day_col)
    self.table_humi_value_text = Gtk.CellRendererText()
    self.table_humi_value_col = Gtk.TreeViewColumn("Value", self.table_humi_value_text, text=1)
    self.table_humi_value_col.set_min_width(100)
    self.table_humi_tree.append_column(self.table_humi_value_col)
    self.table_humi_avg_text = Gtk.CellRendererText()
    self.table_humi_avg_col = Gtk.TreeViewColumn("Average Difference", self.table_humi_value_text, text=2)
    self.table_humi_tree.append_column(self.table_humi_avg_col)
    self.table_humi_low_text = Gtk.CellRendererText()
    self.table_humi_low_col = Gtk.TreeViewColumn("Low Difference", self.table_humi_low_text, text=3)
    self.table_humi_tree.append_column(self.table_humi_low_col)
    self.table_humi_high_text = Gtk.CellRendererText()
    self.table_humi_high_col = Gtk.TreeViewColumn("High Difference", self.table_humi_high_text, text=4)
    self.table_humi_tree.append_column(self.table_humi_high_col)
    self.table_humi_med_text = Gtk.CellRendererText()
    self.table_humi_med_col = Gtk.TreeViewColumn("Median Difference", self.table_humi_med_text, text=5)
    self.table_humi_tree.append_column(self.table_humi_med_col)
    self.table_humi_box.pack_start(self.table_humi_tree, fill=True, expand=True, padding=0)

    # Tab 6: Air Pressure table.
    self.table_airp_box = Gtk.Box()
    self.table_airp_box_lbl = Gtk.Label("Air Pressure")
    self.table_airp_list = Gtk.ListStore(str, str, str, str, str, str)
    self.table_airp_tree = Gtk.TreeView(model=self.table_airp_list)
    self.table_airp_day_text = Gtk.CellRendererText()
    self.table_airp_day_col = Gtk.TreeViewColumn("Day", self.table_airp_day_text, text=0)
    self.table_airp_day_col.set_min_width(150)
    self.table_airp_tree.append_column(self.table_airp_day_col)
    self.table_airp_value_text = Gtk.CellRendererText()
    self.table_airp_value_col = Gtk.TreeViewColumn("Value", self.table_airp_value_text, text=1)
    self.table_airp_value_col.set_min_width(100)
    self.table_airp_tree.append_column(self.table_airp_value_col)
    self.table_airp_avg_text = Gtk.CellRendererText()
    self.table_airp_avg_col = Gtk.TreeViewColumn("Average Difference", self.table_airp_value_text, text=2)
    self.table_airp_tree.append_column(self.table_airp_avg_col)
    self.table_airp_low_text = Gtk.CellRendererText()
    self.table_airp_low_col = Gtk.TreeViewColumn("Low Difference", self.table_airp_low_text, text=3)
    self.table_airp_tree.append_column(self.table_airp_low_col)
    high_text5 = Gtk.CellRendererText()
    self.table_airp_high_col = Gtk.TreeViewColumn("High Difference", high_text5, text=4)
    self.table_airp_tree.append_column(self.table_airp_high_col)
    self.table_airp_med_text = Gtk.CellRendererText()
    self.table_airp_med_col = Gtk.TreeViewColumn("Median Difference", self.table_airp_med_text, text=5)
    self.table_airp_tree.append_column(self.table_airp_med_col)
    self.table_airp_box.pack_start(self.table_airp_tree, fill=True, expand=True, padding=0)

    # Tab 7: Visibility table.
    self.table_visi_box = Gtk.Box()
    self.table_visi_box_lbl = Gtk.Label("Visibility")
    self.table_visi_list = Gtk.ListStore(str, str, str, str, str, str)
    self.table_visi_tree = Gtk.TreeView(model=self.table_visi_list)
    self.table_visi_day_text = Gtk.CellRendererText()
    self.table_visi_day_col = Gtk.TreeViewColumn("Day", self.table_visi_day_text, text=0)
    self.table_visi_day_col.set_min_width(150)
    self.table_visi_tree.append_column(self.table_visi_day_col)
    self.table_visi_value_text = Gtk.CellRendererText()
    self.table_visi_value_col = Gtk.TreeViewColumn("Value", self.table_visi_value_text, text=1)
    self.table_visi_value_col.set_min_width(100)
    self.table_visi_tree.append_column(self.table_visi_value_col)
    self.table_visi_avg_text = Gtk.CellRendererText()
    self.table_visi_avg_col = Gtk.TreeViewColumn("Average Difference", self.table_visi_value_text, text=2)
    self.table_visi_tree.append_column(self.table_visi_avg_col)
    self.table_visi_low_text = Gtk.CellRendererText()
    self.table_visi_low_col = Gtk.TreeViewColumn("Low Difference", self.table_visi_low_text, text=3)
    self.table_visi_tree.append_column(self.table_visi_low_col)
    self.table_visi_high_text = Gtk.CellRendererText()
    self.table_visi_high_col = Gtk.TreeViewColumn("High Difference", self.table_visi_high_text, text=4)
    self.table_visi_tree.append_column(self.table_visi_high_col)
    self.table_visi_med_text = Gtk.CellRendererText()
    self.table_visi_med_col = Gtk.TreeViewColumn("Median Difference", self.table_visi_med_text, text=5)
    self.table_visi_tree.append_column(self.table_visi_med_col)
    self.table_visi_box.pack_start(self.table_visi_tree, fill=True, expand=True, padding=0)

    # Add the tabs.
    self.table_notebook.append_page(self.table_temp_box, self.table_temp_box_lbl)
    self.table_notebook.append_page(self.table_chil_box, self.table_chil_box_lbl)
    self.table_notebook.append_page(self.table_prec_box, self.table_prec_box_lbl)
    self.table_notebook.append_page(self.table_wind_box, self.table_wind_box_lbl)
    self.table_notebook.append_page(self.table_humi_box, self.table_humi_box_lbl)
    self.table_notebook.append_page(self.table_airp_box, self.table_airp_box_lbl)
    self.table_notebook.append_page(self.table_visi_box, self.table_visi_box_lbl)
